//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestToWork.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeOfOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeOfOperation()
        {
            this.Shops = new HashSet<Shops>();
        }
    
        public int IdMode { get; set; }
        public Nullable<int> Monday { get; set; }
        public Nullable<int> Tuesday { get; set; }
        public Nullable<int> Wednesday { get; set; }
        public Nullable<int> Thursday { get; set; }
        public Nullable<int> Friday { get; set; }
        public Nullable<int> Saturday { get; set; }
        public Nullable<int> Sunday { get; set; }
    
        public virtual BeginAndEndWork BeginAndEndWork { get; set; }
        public virtual BeginAndEndWork BeginAndEndWork1 { get; set; }
        public virtual BeginAndEndWork BeginAndEndWork2 { get; set; }
        public virtual BeginAndEndWork BeginAndEndWork3 { get; set; }
        public virtual BeginAndEndWork BeginAndEndWork4 { get; set; }
        public virtual BeginAndEndWork BeginAndEndWork5 { get; set; }
        public virtual BeginAndEndWork BeginAndEndWork6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shops> Shops { get; set; }
    }
}
